version: "3.9"

services:
  api:
    container_name: auth-server
    image: usmansbk/auth-server
    restart: always
    build: .
    env_file: .env
    depends_on:
      - db
      - cache
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  db:
    container_name: postgresql_db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user-pool
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    container_name: redis-server
    image: redis:6-alpine
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  node_modules:
  db:
    driver: local
  cache:
    driver: local
