version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
      - image: cimg/redis:6.2.6
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_pool_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Create secrets folder
          command: mkdir certs
      - run:
          name: Generate JWT private key
          command: ssh-keygen -t rsa -P "" -b 4096 -m PEM -f certs/jwtRS256.key
      - run:
          name: Generate JWT public key
          command: ssh-keygen -e -m PEM -f certs/jwtRS256.key > certs/jwtRS256.key.pub
      - run:
          name: Run tests
          command: yarn test
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: yarn docker:build:prod
