version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
      - image: cimg/redis:6.2.6
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_pool_test
    steps:
      - checkout
      - run: yarn install
      - run: mkdir certs
      - run: ssh-keygen -t rsa -P "" -b 4096 -m PEM -f certs/jwtRS256.key
      - run: ssh-keygen -e -m PEM -f certs/jwtRS256.key > certs/jwtRS256.key.pub
      - run: yarn test
