version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.15.1
      - image: cimg/redis:6.2.6
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_pool_test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Create secrets folder
          command: mkdir certs
      - run:
          name: Generate JWT private key
          command: ssh-keygen -t rsa -P "" -b 4096 -m PEM -f certs/jwtRS256.key
      - run:
          name: Generate JWT public key
          command: ssh-keygen -e -m PEM -f certs/jwtRS256.key > certs/jwtRS256.key.pub
      - run:
          name: Run tests
          command: yarn test
