version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.15.1
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_pool_ci
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Create secrets folder
          command: mkdir certs
      - run:
          name: Generate JWT private key
          command: openssl genrsa -out certs/private.key 2048
      - run:
          name: Generate JWT public key
          command: openssl rsa -in certs/private.key -pubout -outform PEM -out certs/public.pem
      - run:
          name: Run tests
          command: yarn test
  build_and_deploy:
    docker:
      - image: cimg/node:16.15.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build --target prod -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
workflows:
  build_test_deploy:
    jobs:
      - test:
          context:
            - docker-hub-creds
          filters:
            branches:
              only:
                - release
                - staging
                - develop
      - build_and_deploy:
          context:
            - docker-hub-creds
          requires:
            - test
          filters:
            branches:
              only:
                - release
                - staging
