version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
      - image: cimg/redis:6.2.6
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_pool_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Create secrets folder
          command: mkdir certs
      - run:
          name: Generate JWT private key
          command: ssh-keygen -t rsa -P "" -b 4096 -m PEM -f certs/jwtRS256.key
      - run:
          name: Generate JWT public key
          command: ssh-keygen -e -m PEM -f certs/jwtRS256.key > certs/jwtRS256.key.pub
      - run:
          name: Run tests
          command: yarn test
          environment:
            TEST_CLIENT_ID: test
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_NAME: user_pool_test
            DB_NAME_TEST: user_pool_test
            DB_HOST: localhost
            DB_DIALECT: postgres
            DB_PORT: 5432

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: docker build . --tag usmansbk/auth-server:{{ .Branch }} --target prod
